### ISSUE TITLE
[Feature request] Option for backspace to not contribute to combos

### ISSUE THREAD

**Issue by Anarchtism** [zhouhua/obsidian-power-mode#5]
Would be nice if backspace could be set to not contribute to combos!

**Comment by zhouhua** [comment]
I can determine whether to increase the combo count by listening for the backspace key press. But if I do that, things can get complicated. Should I also consider cases like cmd + x, cmd + z, or even cmd + d.

Actually, this combo serves as a constant source of encouragement, giving us more energy to do some tedious tasks. So, why take the number so seriously? As long as it shows that we're working, it's fine. After all, who can say that removing incorrect text isn't part of creating meaningful content?

Of course, these are just my personal thoughts.

**Comment by Anarchtism** [comment]
Well, I'm just trying to get better at typing faster without making mistakes. Plus it's also fun if doing [stream-of-consciousness writing](https://en.wikipedia.org/wiki/Stream_of_consciousness) to have the combo loss remind me what I'm doing.

**Comment by zhouhua** [comment]
Interesting, this is an area I'm not familiar with. Maybe I can add a setting to control this. Moreover, instead of listening for key events, perhaps I can determine whether to count towards the combo by checking if the document word count has increased.

**Comment by zhouhua** [comment]
I just released a version that should meet your needs.
