### ISSUE TITLE
当关闭标签页，重新打开标签页编辑的时候，combo 会失效

### ISSUE THREAD

**Issue by qian-shen** [zhouhua/obsidian-power-mode#7]
当关闭当前标签页，重新打开的时候，combo 会失去效果，并且如果有多个标签页，combo 只会作用在当前打开的标签页上，其他标签页无效果。

**Comment by zhouhua** [comment]
在 #6 中也提到了这个问题，我已经修复了，但由于一些别的问题还没有完全改完，所以没有发布新版本，我尽快完成。

**Comment by qian-shen** [comment]
> 在 #6 中也提到了这个问题，我已经修复了，但由于一些别的问题还没有完全改完，所以没有发布新版本，我尽快完成。

好的，辛苦作者了，期待新版本

**Comment by zhouhua** [comment]
我发布了新版本，欢迎再体验一下

**Comment by qian-shen** [comment]
> 我发布了新版本，欢迎再体验一下

好的！
